import { SUPPORTED_MODELS, SUPPORTED_PROVIDERS, SUPPORTED_VARIANTS } from "./registry";
import type { ModelRequirement } from "./model-requirement-types"

export const AGENT_MODEL_REQUIREMENTS: Record<string, ModelRequirement> = {
  sisyphus: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      { providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING], model: SUPPORTED_MODELS.KIMI_K2P5 },
      {
        providers: [
          SUPPORTED_PROVIDERS.OPENCODE,
          SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN,
          SUPPORTED_PROVIDERS.MOONSHOTAI,
          SUPPORTED_PROVIDERS.MOONSHOTAI_CN,
          SUPPORTED_PROVIDERS.FIRMWARE,
          SUPPORTED_PROVIDERS.OLLAMA_CLOUD,
          SUPPORTED_PROVIDERS.AIHUBMIX,
          SUPPORTED_PROVIDERS.VERCEL,
        ],
        model: SUPPORTED_MODELS.KIMI_K2_5,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_5, variant: SUPPORTED_VARIANTS.MEDIUM },
      { providers: [SUPPORTED_PROVIDERS.ZAI_CODING_PLAN, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE], model: SUPPORTED_MODELS.BIG_PICKLE },
    ],
    requiresAnyModel: true,
  },
  hephaestus: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
    ],
    requiresProvider: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
    requiresAnyModel: true,
  },
  oracle: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
    ],
  },
  librarian: {
    fallbackChain: [
      { providers: [SUPPORTED_PROVIDERS.OPENAI], model: SUPPORTED_MODELS.GPT_5_4_MINI_FAST },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN], model: SUPPORTED_MODELS.QWEN_3_5_PLUS },
      { providers: [SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7_HIGHSPEED },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_CAP },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
      { providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.CLAUDE_HAIKU_4_5 },
      { providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_4_NANO },
    ],
  },
  explore: {
    fallbackChain: [
      { providers: [SUPPORTED_PROVIDERS.OPENAI], model: SUPPORTED_MODELS.GPT_5_4_MINI_FAST },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN], model: SUPPORTED_MODELS.QWEN_3_5_PLUS },
      { providers: [SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7_HIGHSPEED },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_CAP },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
      { providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.CLAUDE_HAIKU_4_5 },
      { providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_4_NANO },
    ],
  },
  "multimodal-looker": {
    fallbackChain: [
      { providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_5, variant: SUPPORTED_VARIANTS.MEDIUM },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      { providers: [SUPPORTED_PROVIDERS.ZAI_CODING_PLAN, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_4_6V },
      { providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_NANO },
    ],
  },
  prometheus: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
      },
    ],
  },
  metis: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_SONNET_4_6,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
      { providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING], model: SUPPORTED_MODELS.KIMI_K2P5 },
    ],
  },
  momus: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
    ],
  },
  atlas: {
    fallbackChain: [
      { providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.CLAUDE_SONNET_4_6 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_CAP },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
    ],
  },
  "sisyphus-junior": {
    fallbackChain: [
      { providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.CLAUDE_SONNET_4_6 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_CAP },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE], model: SUPPORTED_MODELS.BIG_PICKLE },
    ],
  },
};
