import { SUPPORTED_MODELS, SUPPORTED_PROVIDERS, SUPPORTED_VARIANTS } from "./registry";
import type { ModelRequirement } from "./model-requirement-types"

export const CATEGORY_MODEL_REQUIREMENTS: Record<string, ModelRequirement> = {
  "visual-engineering": {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      { providers: [SUPPORTED_PROVIDERS.ZAI_CODING_PLAN, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5 },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
      { providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING], model: SUPPORTED_MODELS.KIMI_K2P5 },
    ],
  },
  ultrabrain: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
    ],
  },
  deep: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_TERRA,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_SOL,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
    ],
  },
  artistry: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_1_PRO,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_5 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
    ],
  },
  quick: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_4_MINI,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_HAIKU_4_5,
      },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_FLASH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_NATIVE },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GPT_5_NANO },
    ],
  },
  "unspecified-low": {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_6_LUNA,
        variant: SUPPORTED_VARIANTS.XHIGH,
      },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_SONNET_4_6,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.MEDIUM,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_FLASH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_NATIVE },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
    ],
  },
  "unspecified-high": {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_OPUS_4_7,
        variant: SUPPORTED_VARIANTS.MAX,
      },
      {
        providers: [SUPPORTED_PROVIDERS.OPENAI, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GPT_5_5,
        variant: SUPPORTED_VARIANTS.HIGH,
      },
      { providers: [SUPPORTED_PROVIDERS.ZAI_CODING_PLAN, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5 },
      { providers: [SUPPORTED_PROVIDERS.KIMI_FOR_CODING], model: SUPPORTED_MODELS.KIMI_K2P5 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.GLM_5_2 },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_5 },
      {
        providers: [
          SUPPORTED_PROVIDERS.OPENCODE,
          SUPPORTED_PROVIDERS.BAILIAN_CODING_PLAN,
          SUPPORTED_PROVIDERS.MOONSHOTAI,
          SUPPORTED_PROVIDERS.MOONSHOTAI_CN,
          SUPPORTED_PROVIDERS.FIRMWARE,
          SUPPORTED_PROVIDERS.OLLAMA_CLOUD,
          SUPPORTED_PROVIDERS.AIHUBMIX,
          SUPPORTED_PROVIDERS.VERCEL,
        ],
        model: SUPPORTED_MODELS.KIMI_K2_5,
      },
    ],
  },
  writing: {
    fallbackChain: [
      {
        providers: [SUPPORTED_PROVIDERS.GOOGLE, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.GEMINI_3_FLASH,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.KIMI_K2_6 },
      {
        providers: [SUPPORTED_PROVIDERS.ANTHROPIC, SUPPORTED_PROVIDERS.GITHUB_COPILOT, SUPPORTED_PROVIDERS.OPENCODE, SUPPORTED_PROVIDERS.VERCEL],
        model: SUPPORTED_MODELS.CLAUDE_SONNET_4_6,
      },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M3 },
      { providers: [SUPPORTED_PROVIDERS.MINIMAX_CODING_PLAN, SUPPORTED_PROVIDERS.MINIMAX_CN_CODING_PLAN], model: SUPPORTED_MODELS.MINIMAX_M3_NATIVE },
      { providers: [SUPPORTED_PROVIDERS.OPENCODE_GO, SUPPORTED_PROVIDERS.VERCEL], model: SUPPORTED_MODELS.MINIMAX_M2_7 },
    ],
  },
};
